[build]
  command = "npm run build"
  functions = "backend/functions"
  publish = "frontend/dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[dev]
  functions = "backend/functions"
  publish = "frontend/dist"
  port = 8888
  autoLaunch = true