[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "wosweat"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[dev]
  functions = "netlify/functions"
  publish = "wosweat"
  port = 8888
  autoLaunch = true