[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 8888
  autoLaunch = true

[[plugins]]
  package = "@netlify/plugin-functions-scheduled-event"

  [plugins.inputs]
    # Run the scraper function daily at midnight UTC
    scrape-events-function = "scheduled-scrape"
    schedule = "0 0 * * *"